scripts for remote benchmarking
Pepperrs/Cloud-Computing-Benchmark pull request #4
Opened 2017-06-09 14:04 UTC by schasse

2017-06-09 21:51 UTC, Peterschuellermann requested changes
apt-get will not work for AWS which uses yum. Please add distinction.

2017-06-09 21:52 UTC, Pepperrs commented on benchmark.sh
> +printf "Benchmark for: " >> results.txt
">" was correct so it overwrites the last results file and not appends to ti

2017-06-09 21:53 UTC, Pepperrs commented on benchmark.sh
> -rm linpack
the compiled versions might interfere with rsync and are therefore deleted beforehand

2017-06-10 11:56 UTC, schasse commented on benchmark.sh
> +printf "Benchmark for: " >> results.txt
see line `19`. there is the overwriting `>`.

2017-06-10 11:56 UTC, schasse commented on benchmark.sh
> -rm linpack
`remote_benchmark.sh` uses git to upload `results.txt` and the binaries are in `.gitignore`.

2017-06-10 11:56 UTC, schasse commented on benchmark.sh
> +apt-get install -y build-essential
on openstack we need to use apt-get.

2017-06-10 11:56 UTC, schasse commented on benchmark.sh
> +apt-get install -y build-essential
the assignment says we should use 'amazon linux ami'. i don't know which package manager it uses.

2017-06-12 14:46 UTC, Peterschuellermann approved these changes

2017-06-12 14:46 UTC, merged